### ISSUE TITLE
this is more a q then an issue

### ISSUE THREAD

**Issue by frankiebee** [staltz/ssb-keys-mnemonic#1]
why use 48 words? 
https://github.com/staltz/ssb-keys-mnemonic/blob/master/src/index.ts#L30L33

**Comment by staltz** [comment]
Hey @frankiebee ! :)

[BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) encodes 256 bits as 24 words, but we need 512 bits to represent the ed25519 private key, so that multiplies it by 2.

BIP39 is used internally in this module.

Does that answer it?

**Comment by frankiebee** [comment]
yes it does! thank you
